OPENAI_API_KEY: "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"
TAVILY_API_KEY: "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"
MODEL: "gpt-4o-mini"
TEMPERATURE: 0
